### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by pecourses** [Konvaly/homework-js1#4]
https://github.com/Konvaly/homework-js1/blob/080dc4360f768fb52b0a69c487da91bfc7b810a5/js/index.js#L108
- подумайте, какая будет скидка при 800 по коду, а какая должна быть по условию. Вспомните, я оговаривала как тестировать код в такой задаче при разборе дз.

**Comment by Konvaly** [comment]
Исправила.
Конечно, покупателю обидно - при 799 у него скидка есть, а при 800 уже нет ;)
